//package com.example.accessingdatamysql;
//
//
//import com.example.accessingdatamysql.User;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.scheduling.annotation.Async;
//import org.springframework.stereotype.Service;
//
//import java.util.List;
//import java.util.concurrent.CompletableFuture;
//
//@Service
//public class UserService {
//
//    @Autowired
//    // This means to get the bean called userRepository// Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;
//
//    @Async
//    public CompletableFuture<String> addUserToDatabase(User user){
//        try {
//            userRepository.save(user);
//            return CompletableFuture.completedFuture("User added Successfully");
//        }catch (Exception e){
//            System.out.println(e);
//            return CompletableFuture.completedFuture("Database Error");
//
//        }
//    }
//
//
//    public List<User> getAllUsersFromDatabase(){
//        try {
//            return userRepository.findAll();
//        }catch (Exception e){
//            return (List<User>) e;
//        }
//    }
//}
